### ISSUE TITLE
DOWNLOAD_ERROR: UrlHash '"12efde62fc592e6640cc3021bd2bcf37"':'"https://archive.fo/aOwrS"'

### ISSUE THREAD

**Issue by mgnoonan** [mgnoonan/RssFeeder#225]
**Message** [View Event](http://localhost:5341/#/events?filter=@Id%20%3D%20'event-665c9c15c99508d97c871b0100000000')
```
DOWNLOAD_ERROR: UrlHash '"12efde62fc592e6640cc3021bd2bcf37"':'"https://archive.fo/aOwrS"'
```

**Exception**
```
System.ArgumentNullException: Value cannot be null. (Parameter 'uriString')
   at System.Uri..ctor(String uriString)
   at RssFeeder.Console.WebCrawler.ParseAndSave(RssFeed feed, RssFeedItem item) in C:\Projects\RssFeeder\RssFeeder.Console\WebCrawler.cs:line 139
   at RssFeeder.Console.WebCrawler.DownloadList(RssFeed feed, String workingFolder, List`1 list) in C:\Projects\RssFeeder\RssFeeder.Console\WebCrawler.cs:line 199
```

**Properties**
```
* urlHash : "12efde62fc592e6640cc3021bd2bcf37"
* url : "https://archive.fo/aOwrS"
* collectionName : "revolver-news"
```

**Comment by mgnoonan** [comment]
This exception is thrown when the crawler didn't actually download any content. Added a check for this in #224.
