### ISSUE TITLE
The HTTP request to the remote WebDriver server for URL timed out after 60 sec

### ISSUE THREAD

**Issue by mgnoonan** [mgnoonan/RssFeeder#226]
**Message** [View Event](http://seq:5341/#/events?filter=@Id%20%3D%20'event-6df3e269c9d808d9f7f11b0100000000')
```
WebDriverUrlToDisk: '"b24bac4707bc52c6a4390c6afa3c4463"':'"https://t.co/8oAZwZxU2R"' - Unexpected error '"The HTTP request to the remote WebDriver server for URL http://localhost:50359/session/264f704684280bc44901a9b64273774d/url timed out after 60 seconds."'
```

**Exception**
```
OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:50359/session/264f704684280bc44901a9b64273774d/url timed out after 60 seconds.
 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 60 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.set_Url(String value)
   at OpenQA.Selenium.Navigator.GoToUrl(String url)
   at RssFeeder.Console.Utility.WebUtils.WebDriverUrlToDisk(String url, String urlHash, String filename) in C:\Projects\RssFeeder\RssFeeder.Console\Utility\WebUtils.cs:line 119
```

**Properties**
```
* urlHash : "b24bac4707bc52c6a4390c6afa3c4463"
* url : "https://t.co/8oAZwZxU2R"
* message : "The HTTP request to the remote WebDriver server for URL http://localhost:50359/session/264f704684280bc44901a9b64273774d/url timed out after 60 seconds."
* collectionName : "bad-blue"
```

**Comment by mgnoonan** [comment]
THis is related to #247

**Comment by mgnoonan** [comment]
Closing this, we have moved away from the flow that created this issue.
