### ISSUE TITLE
GetHostName fails with encoded URLs

### ISSUE THREAD

**Issue by mgnoonan** [mgnoonan/RssFeeder#228]
**Message** [View Event](http://seq:5341/#/events?filter=@Id%20%3D%20'event-1143b8adca1308d9915e1c0100000000')
```
PARSE_ERROR: UrlHash '"1b9521d0a0869447378b7829e2785c97"':'"https://t.co/6bCh6H04GW"'
```

**Exception**
```
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at RssFeeder.Console.ArticleParser.GetHostName(RssFeedItem item) in C:\Projects\RssFeeder\RssFeeder.Console\ArticleParser.cs:line 62
   at RssFeeder.Console.ArticleParser.Parse(RssFeedItem item) in C:\Projects\RssFeeder\RssFeeder.Console\ArticleParser.cs:line 58
   at RssFeeder.Console.WebCrawler.ParseAndSave(RssFeed feed, RssFeedItem item) in C:\Projects\RssFeeder\RssFeeder.Console\WebCrawler.cs:line 139
```

**Properties**
```
* urlHash : "1b9521d0a0869447378b7829e2785c97"
* url : "https://t.co/6bCh6H04GW"
* collectionName : "bad-blue"
```

**Comment by mgnoonan** [comment]
This is because the starting value is the og:url value, which is encoded:
![image](https://user-images.githubusercontent.com/3255096/147580434-690bbd05-b82d-4fea-a167-741032feffbc.png)

Consider decoding all og tag values, or maybe look for the encoding and try to decode it.
