### ISSUE TITLE
Add handling for PDF links

### ISSUE THREAD

**Issue by mgnoonan** [mgnoonan/RssFeeder#259]
**Message** [View Event](http://seq:5341/#/events?filter=@Id%20%3D%20'event-811e6e2949f608da56f9740100000000')
```
Error parsing paragraph selectors '"p"', '"The string did not match the expected pattern."'
```

**Exception**
```
AngleSharp.Dom.DomException: The string did not match the expected pattern.
   at AngleSharp.Dom.QueryExtensions.CreateSelector(INodeList nodes, INode scope, String selectorText)
   at AngleSharp.Dom.QueryExtensions.QuerySelector(INodeList nodes, String selectorText, INode scopeNode)
   at RssFeeder.Console.TagParsers.AdaptiveTagParser.GetArticleText(IHtmlDocument document, String bodySelector, String paragraphSelector) in C:\Projects\RssFeeder\RssFeeder.Console\TagParsers\AdaptiveTagParser.cs:line 43
```

**Properties**
```
* paragraphSelector : "p"
* message : "The string did not match the expected pattern."
* siteName : "irp.fas.org"
* urlHash : "f91578f4abfea8827f4e8399da465a98"
* url : "https://t.co/pNOBI2tUQX"
* runID : "0f3c1aad-d5b6-42b2-8e63-7632a10c0fd9"
* collectionName : "bad-blue"
* Application : "rssfeeder.crawler"
```

**Comment by mgnoonan** [comment]
Apparently this is an issue with PDF links.
```json
{
    "@t": "2022-06-09T09:00:28.7512361Z",
    "@mt": "Response status code = {intStatusCode} {statusCode}, {uri}",
    "@m": "Response status code = 200 OK, https://irp.fas.org/doddir/army/fm3-05-301.pdf",
    "@i": "1c2f2164",
    "intStatusCode": 200,
    "statusCode": "OK",
    "uri": "https://irp.fas.org/doddir/army/fm3-05-301.pdf",
    "urlHash": "f91578f4abfea8827f4e8399da465a98",
    "url": "https://t.co/pNOBI2tUQX",
    "runID": "0f3c1aad-d5b6-42b2-8e63-7632a10c0fd9",
    "collectionName": "bad-blue",
    "Application": "rssfeeder.crawler"
}
```
