### ISSUE TITLE
ERROR: Unable to process feed '"Revolver News"' from '"https://www.revolver.news/"'

### ISSUE THREAD

**Issue by mgnoonan** [mgnoonan/RssFeeder#266]
**Message** [View Event](http://seq:5341/#/events?filter=@Id%20%3D%20'event-4e4939e05aa908da30ab780100000000')
```
ERROR: Unable to process feed '"Revolver News"' from '"https://www.revolver.news/"'
```

**Exception**
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at RssFeeder.Console.FeedBuilders.RevolverNewsFeedBuilder.GenerateRssFeedItemList(String html, List`1 filters, String feedUrl) in C:\Projects\RssFeeder\RssFeeder.Console\FeedBuilders\RevolverNewsFeedBuilder.cs:line 32
   at RssFeeder.Console.FeedBuilders.RevolverNewsFeedBuilder.GenerateRssFeedItemList(String feedCollectionName, String feedUrl, List`1 feedFilters, String html) in C:\Projects\RssFeeder\RssFeeder.Console\FeedBuilders\RevolverNewsFeedBuilder.cs:line 16
   at RssFeeder.Console.FeedBuilders.RevolverNewsFeedBuilder.GenerateRssFeedItemList(RssFeed feed, String html) in C:\Projects\RssFeeder\RssFeeder.Console\FeedBuilders\RevolverNewsFeedBuilder.cs:line 11
   at RssFeeder.Console.WebCrawler.GenerateFeedLinks(RssFeed feed, String workingFolder) in C:\Projects\RssFeeder\RssFeeder.Console\WebCrawler.cs:line 204
   at RssFeeder.Console.WebCrawler.Crawl(Guid runID, RssFeed feed) in C:\Projects\RssFeeder\RssFeeder.Console\WebCrawler.cs:line 49
   at RssFeeder.Console.Commands.BuildCommand.Execute(BuildInput input) in C:\Projects\RssFeeder\RssFeeder.Console\Commands\BuildCommand.cs:line 64
```

**Properties**
```
* feedTitle : "Revolver News"
* feedUrl : "https://www.revolver.news/"
* Application : "rssfeeder.crawler"
```

**Comment by mgnoonan** [comment]
Looks like they changed their content markup and the crawler needs an adjustment.
