### ISSUE TITLE
Error parsing paragraph selectors '"p"', '"The string did not match the expected pattern."'

### ISSUE THREAD

**Issue by mgnoonan** [mgnoonan/RssFeeder#271]
**Message** [View Event](http://seq:5341/#/events?filter=@Id%20%3D%20'event-d026ba6570d308da87557e0100000000')
```
Error parsing paragraph selectors '"p"', '"The string did not match the expected pattern."'
```

**Exception**
```
AngleSharp.Dom.DomException: The string did not match the expected pattern.
   at AngleSharp.Dom.QueryExtensions.CreateSelector(INodeList nodes, INode scope, String selectorText)
   at AngleSharp.Dom.QueryExtensions.QuerySelector(INodeList nodes, String selectorText, INode scopeNode)
   at RssFeeder.Console.TagParsers.AdaptiveTagParser.GetArticleText(IHtmlDocument document, String bodySelector, String paragraphSelector) in C:\Projects\RssFeeder\RssFeeder.Console\TagParsers\AdaptiveTagParser.cs:line 43
```

**Properties**
```
* paragraphSelector : "p"
* message : "The string did not match the expected pattern."
* siteName : "freebeacon.com"
* urlHash : "8da207112ff21289b3eb138b2acbfd3a"
* url : "https://t.co/3l63VZY7Tz"
* runID : "17c3fa7d-f9fc-4416-b80b-12fc07efbcf1"
* collectionName : "bad-blue"
* Application : "rssfeeder.crawler"
```

**Comment by mgnoonan** [comment]
Because this is a shortened url, the PDF handling did not pick it up. Need to either switch out the PDF detection to the real url, or perhaps take into account the MIME type from the download.

This is similar to #259 but a different use case for the detection. That issue uses the presence of the .pdf extension in the URL to detect PDFs. That will not be the case here.

**Comment by mgnoonan** [comment]
If we swith to MIME type detection rather than embedded file extensions in the URL, this may handle both this case and #270 .

**Comment by mgnoonan** [comment]
Currently open question is, can we get the MIME type from Selenium. The WebDriver does not support as many options as the RestSharp client.

**Comment by mgnoonan** [comment]
I don't really have a clear path forward for any of the edge cases, mainly the ones where the URL doesn't give a hint as to the Content-Type by adding `.pdf` or `.gif` within the Url. Right now, the default HttpClient in the crawler assumes the download is  text/html (which is really just a special case of text/plain) and calls `GetAsync()` to retrieve the string content. If the crawler detects binary data because the Url indicates `.pdf`, `.gif`, etc. then the crawler calls `DownloadData()` as a byte array instead.

So what I am thinking as of now is, there are a few options.

1. Issue a HTTP HEAD request first. Rather than just go straight for the GET to retrieve the content, HEAD returns the all the headers without the content, but would give a better indication of the actual type of the content. However, I see this as problematic. Not all the sites in the crawl list will support HEAD requests, but I suppose there could be a fallback mechanism with a default of text/html.
2. Rework the crawler to always use `DownloadData()` and convert the byte array to a string representation where required. This feels wrong for a couple of reasons. There are going to be encoding problems (although those exist now) and probably the biggest reason is that it is the default case. Most of the downloads are going to be text/html, so this seems like a lot of complexity to handle edge cases.

More thoughts as they happen...

**Comment by mgnoonan** [comment]
Resolved to run an experiment on the viability of using HEAD requests, maybe just using one feed only, like Drudge. There will be no decisions made on the outcome of the HEAD request, but instead just gather some data to get a feel for how ubiquitous the support is with the content providers.

If support runs deep, then this becomes a viable alternative. If not, back to the drawing board.

**Comment by mgnoonan** [comment]
Check that, let's use Bad Blue instead. Much higher content rotation, although the content sites might be considered less mainstream. Ah what the hell, let's do both.
