### ISSUE TITLE
Invalid URI: The hostname could not be parsed.

### ISSUE THREAD

**Issue by mgnoonan** [mgnoonan/RssFeeder#274]
**Message** [View Event](http://seq:5341/#/events?filter=@Id%20%3D%20'event-93b511f0726e08dabdb17e0100000000')
```
PARSE_ERROR: UrlHash '"c55585436f5383b238defa9581877475"':'"https://www.toddstarnes.com/uncategorized/biden-has-covid-again/"'
```

**Exception**
```
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at RssFeeder.Console.ArticleParser.GetHostName(RssFeedItem item) in C:\Projects\RssFeeder\RssFeeder.Console\ArticleParser.cs:line 130
   at RssFeeder.Console.ArticleParser.Parse(RssFeedItem item) in C:\Projects\RssFeeder\RssFeeder.Console\ArticleParser.cs:line 69
   at RssFeeder.Console.WebCrawler.TryParseAndSave(RssFeed feed, RssFeedItem item) in C:\Projects\RssFeeder\RssFeeder.Console\WebCrawler.cs:line 100
```

**Properties**
```
* urlHash : "c55585436f5383b238defa9581877475"
* url : "https://www.toddstarnes.com/uncategorized/biden-has-covid-again/"
* runID : "ef25930d-4cde-4cbd-8fc6-26007991f6eb"
* collectionName : "conservagator"
* Application : "rssfeeder.crawler"
```

**Comment by mgnoonan** [comment]
Still investigating why this exception was thrown, because it sure looks valid to me. Might be an encoding issue or something like that.

**Comment by mgnoonan** [comment]
Found the issue, somebody wasn't constructing their OpenGraph attributes correctly.
```html
<meta property="og:url" content="http://Biden%20Has%20Covid%20Again" />
```
There's no clear fix for this, and parsing could still continue even with the bad value, but I'm going to have to think about a good solution for this one off error.
