### ISSUE TITLE
ERROR: Unable to process feed '"Bongino Report"' from '"https://bonginoreport.com/"'

### ISSUE THREAD

**Issue by mgnoonan** [mgnoonan/RssFeeder#278]
**Message** [View Event](http://seq:5341/#/events?filter=@Id%20%3D%20'event-f5ca56a6807108da9848820100000000')
```
ERROR: Unable to process feed '"Bongino Report"' from '"https://bonginoreport.com/"'
```

**Exception**
```
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[RssFeeder.Console.Exporters.JsonLdRumbleValues]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path '@context', line 1, position 12.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at RssFeeder.Console.Exporters.BaseArticleExporter.SetVideoMetaData(ExportFeedItem exportFeedItem, RssFeedItem item, String hostName) in C:\Projects\RssFeeder\RssFeeder.Console\Exporters\BaseArticleExporter.cs:line 118
   at RssFeeder.Console.Exporters.ArticleExporter.FormatItem(RssFeedItem item, RssFeed feed) in C:\Projects\RssFeeder\RssFeeder.Console\Exporters\ArticleExporter.cs:line 51
   at RssFeeder.Console.WebCrawler.Export(Guid runID, RssFeed feed, DateTime startDate) in C:\Projects\RssFeeder\RssFeeder.Console\WebCrawler.cs:line 252
   at RssFeeder.Console.Commands.BuildCommand.Execute(BuildInput input) in C:\Projects\RssFeeder\RssFeeder.Console\Commands\BuildCommand.cs:line 65
```

**Properties**
```
* feedTitle : "Bongino Report"
* feedUrl : "https://bonginoreport.com/"
* Application : "rssfeeder.crawler"
```

**Comment by mgnoonan** [comment]
Also related to #277

**Comment by mgnoonan** [comment]
This may be signaling a change to the JSON format that Rumble is using, but this error has only happened twice (and on the same day?) so I am inclined to ignore this for now. The issue can always be revisited later if more instances pop up. Closing.
