### ISSUE TITLE
SaveUrlToDisk: Unexpected error '"Request timed out"'

### ISSUE THREAD

**Issue by mgnoonan** [mgnoonan/RssFeeder#279]
**Message** [View Event](http://seq:5341/#/events?filter=@Id%20%3D%20'event-51e6270c837508dad410830100000000')
```
SaveUrlToDisk: Unexpected error '"Request timed out"'
```

**Exception**
```
System.TimeoutException: Request timed out
 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at RestSharp.RestClient.ExecuteInternal(RestRequest request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at RestSharp.ResponseThrowExtension.ThrowIfError(RestResponse response)
   at RestSharp.RestClientExtensions.GetAsync(RestClient client, RestRequest request, CancellationToken cancellationToken)
   at RssFeeder.Console.HttpClients.RestSharpHttpClient.GetString(String url) in C:\Projects\RssFeeder\RssFeeder.Console\HttpClients\RestSharpHttpClient.cs:line 37
   at RssFeeder.Console.Utility.WebUtils.TrySaveUrlToDisk(String url, String urlHash, String filename, Boolean removeScriptElements) in C:\Projects\RssFeeder\RssFeeder.Console\Utility\WebUtils.cs:line 30
```

**Properties**
```
* message : "Request timed out"
* urlHash : "6f8d72a2781fcd694182e83408509492"
* url : "https://www.nasdaq.com/articles/the-paycheck-has-died%3A-argentine-workers-hold-funeral-for-wages"
* runID : "45990b77-8064-4668-b505-847a4d0a8c5c"
* collectionName : "drudge-report"
* Application : "rssfeeder.crawler"
```

**Comment by mgnoonan** [comment]
Let's set the flag to retry the crawl with Selenium.
