### ISSUE TITLE
PARSE_ERROR: UrlHash '"c26b2e16328d6257d8989d3952479ea6"':'"https://t.co/hWie6QvPLl"'

### ISSUE THREAD

**Issue by mgnoonan** [mgnoonan/RssFeeder#318]
**Message** [View Event](http://seq:5341/#/events?filter=@Id%20%3D%20'event-0cb280b0abbb08daee888f0100000000')
```
PARSE_ERROR: UrlHash '"c26b2e16328d6257d8989d3952479ea6"':'"https://t.co/hWie6QvPLl"'
```

**Exception**
```
AngleSharp.Dom.DomException: The string did not match the expected pattern.
   at AngleSharp.Dom.QueryExtensions.CreateSelector(INodeList nodes, INode scope, String selectorText)
   at AngleSharp.Dom.QueryExtensions.QuerySelectorAll(INodeList nodes, String selectorText, INode scopeNode)
   at AngleSharp.Dom.ElementExtensions.GetSelector(IElement element)
   at RssFeeder.Console.TagParsers.AdaptiveTagParser.GetHighestParagraphCountSelector(IHtmlDocument document, String paragraphSelector, Boolean skipIfEmptyContent) in C:\Projects\RssFeeder\RssFeeder.Console\TagParsers\AdaptiveTagParser.cs:line 77
   at RssFeeder.Console.TagParsers.AdaptiveTagParser.ParseTagsBySelector(ArticleRouteTemplate template) in C:\Projects\RssFeeder\RssFeeder.Console\TagParsers\AdaptiveTagParser.cs:line 18
   at RssFeeder.Console.ArticleParser.Parse(RssFeedItem item) in C:\Projects\RssFeeder\RssFeeder.Console\ArticleParser.cs:line 73
   at RssFeeder.Console.WebCrawler.TryParseAndSave(RssFeed feed, RssFeedItem item) in C:\Projects\RssFeeder\RssFeeder.Console\WebCrawler.cs:line 101
```

**Properties**
```
* urlHash : "c26b2e16328d6257d8989d3952479ea6"
* url : "https://t.co/hWie6QvPLl"
* variation : "new"
* runID : "69cd8f57-6400-49ea-85ce-f5761b13d87f"
* collectionName : "bad-blue"
* Application : "rssfeeder.crawler"
```

**Comment by mgnoonan** [comment]
Noticing some markup above the DOCTYPE tag, so this may be what is generating the error.
```html
<br>
<b>Notice</b>: MemcachePool::get() [<a href='memcachepool.get'>memcachepool.get</a>]: Server
legacy-redis-master.legacy-prod.svc.cluster.local (tcp 6379, udp 0) failed with: Malformed VALUE header (0) in
<b>/var/www/html/sites/all/modules/memcache/dmemcache.inc</b> on line <b>63</b><br>
<br>
<b>Warning</b>: Cannot modify header information - headers already sent by (output started at
/var/www/html/sites/all/modules/memcache/dmemcache.inc:63) in <b>/var/www/html/includes/bootstrap.inc</b> on line
<b>582</b><br>
<br>
<b>Warning</b>: Cannot modify header information - headers already sent by (output started at
/var/www/html/sites/all/modules/memcache/dmemcache.inc:63) in <b>/var/www/html/includes/bootstrap.inc</b> on line
<b>583</b><br>
<br>
<b>Warning</b>: Cannot modify header information - headers already sent by (output started at
/var/www/html/sites/all/modules/memcache/dmemcache.inc:63) in <b>/var/www/html/includes/bootstrap.inc</b> on line
<b>584</b><br>
<br>
<b>Warning</b>: Cannot modify header information - headers already sent by (output started at
/var/www/html/sites/all/modules/memcache/dmemcache.inc:63) in <b>/var/www/html/includes/bootstrap.inc</b> on line
<b>585</b><br>
<!DOCTYPE html
      PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
```

**Comment by mgnoonan** [comment]
It's possible the malformed HTML markup is causing the error. Probably not going to fix that aspect but maybe look at better handling of the error. Not sure yet.
