### ISSUE TITLE
Error when parser encounters an invalid relative URL

### ISSUE THREAD

**Issue by mgnoonan** [mgnoonan/RssFeeder#348]
**Message** [View Event](http://seq:5341/#/events?filter=@Id%20%3D%20'event-14e8c297fb2a08da9567a90100000000')
```
PARSE_ERROR: UrlHash '"97dccd71387a20a80fbf34245b7de57c"':'"https://offthepress.com/florida-rejects-ap-african-american-studies-cites-political-agenda/"'
```

**Exception**
```
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri.CreateUri(Uri baseUri, String relativeUri, Boolean dontEscape)
   at RssFeeder.Console.Utility.WebUtils.RepairUrl(String relativeUrl, Uri baseUri) in C:\Projects\RssFeeder\RssFeeder.Console\Utility\WebUtils.cs:line 336
   at RssFeeder.Console.Utility.WebUtils.RepairUrl(String relativeUrl, String defaultBaseUrl) in C:\Projects\RssFeeder\RssFeeder.Console\Utility\WebUtils.cs:line 322
   at RssFeeder.Console.TagParsers.TagParserBase.ReplaceTagAttribute(IHtmlDocument document, String baseUrl, String tagName, String attributeName, Boolean addMissing) in C:\Projects\RssFeeder\RssFeeder.Console\TagParsers\TagParserBase.cs:line 201
   at RssFeeder.Console.TagParsers.TagParserBase.PostParse() in C:\Projects\RssFeeder\RssFeeder.Console\TagParsers\TagParserBase.cs:line 36
   at RssFeeder.Console.ArticleParser.Parse(RssFeedItem item) in C:\Projects\RssFeeder\RssFeeder.Console\ArticleParser.cs:line 73
   at RssFeeder.Console.WebCrawler.TryParseAndSave(RssFeed feed, RssFeedItem item) in C:\Projects\RssFeeder\RssFeeder.Console\WebCrawler.cs:line 101
```

**Properties**
```
* urlHash : "97dccd71387a20a80fbf34245b7de57c"
* url : "https://offthepress.com/florida-rejects-ap-african-american-studies-cites-political-agenda/"
* runID : "aa56b6fe-69d9-4c2d-b345-229f90d10e0a"
* collectionName : "off-the-press"
* Application : "rssfeeder.crawler"
```

**Comment by mgnoonan** [comment]
Looks like somebody didn't check their PDF links before content publish.
![image](https://user-images.githubusercontent.com/3255096/213806897-36d0d49d-1312-4c27-9ce6-ac6ff38136b8.png)
