### ISSUE TITLE
ERROR: Unable to process feed '"Whatfinger News"' from '"https://www.whatfinger.com/home2/"'

### ISSUE THREAD

**Issue by mgnoonan** [mgnoonan/RssFeeder#349]
**Message** [View Event](http://seq:5341/#/events?filter=@Id%20%3D%20'event-2ebc6211fc8108da9ac7a90100000000')
```
ERROR: Unable to process feed '"Whatfinger News"' from '"https://www.whatfinger.com/home2/"'
```

**Exception**
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at RssFeeder.Console.FeedBuilders.BaseFeedBuilder.CreateNodeLinks(List`1 filters, IElement node, String location, Int32 count, String feedUrl, Boolean isHeadline) in C:\Projects\RssFeeder\RssFeeder.Console\FeedBuilders\BaseFeedBuilder.cs:line 42
   at RssFeeder.Console.FeedBuilders.WhatFingerFeedBuilder.GenerateRssFeedItemList(String html, List`1 filters, String feedUrl) in C:\Projects\RssFeeder\RssFeeder.Console\FeedBuilders\WhatFingerFeedBuilder.cs:line 69
   at RssFeeder.Console.FeedBuilders.WhatFingerFeedBuilder.GenerateRssFeedItemList(String feedCollectionName, String feedUrl, List`1 feedFilters, String html) in C:\Projects\RssFeeder\RssFeeder.Console\FeedBuilders\WhatFingerFeedBuilder.cs:line 39
   at RssFeeder.Console.FeedBuilders.WhatFingerFeedBuilder.GenerateRssFeedItemList(RssFeed feed, String html) in C:\Projects\RssFeeder\RssFeeder.Console\FeedBuilders\WhatFingerFeedBuilder.cs:line 34
   at RssFeeder.Console.WebCrawler.GenerateFeedLinks(RssFeed feed) in C:\Projects\RssFeeder\RssFeeder.Console\WebCrawler.cs:line 291
   at RssFeeder.Console.WebCrawler.Crawl(Guid runID, RssFeed feed) in C:\Projects\RssFeeder\RssFeeder.Console\WebCrawler.cs:line 51
   at RssFeeder.Console.Commands.BuildCommand.Execute(BuildInput input) in C:\Projects\RssFeeder\RssFeeder.Console\Commands\BuildCommand.cs:line 71
```

**Properties**
```
* feedTitle : "Whatfinger News"
* feedUrl : "https://www.whatfinger.com/home2/"
* runID : "969c21cc-cc83-4b68-a59b-d0ab45fb6efc"
* collectionName : "whatfinger"
* Application : "rssfeeder.crawler"
```

**Comment by mgnoonan** [comment]
Situation resolved itself.
