### ISSUE TITLE
ArgumentOutOfRangeException in TryAddUlParagraph

### ISSUE THREAD

**Issue by mgnoonan** [mgnoonan/RssFeeder#352]
**Message** [View Event](http://seq:5341/#/events?filter=@Id%20%3D%20'event-d614d79b172708dbcd48b30100000000')
```
PARSE_ERROR: UrlHash '"feee7afb66be800f6e6065d53269b5ae"':'"https://tulsaworld.com/news/state-and-regional/govt-and-politics/jim-inhofe-looks-back-on-his-career-i-really-wanted-to-make-a-difference-and/article_3e824aaa-9750-11ed-9be6-2fe21d735cfe.html"'
```

**Exception**
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at AngleSharp.Common.ObjectExtensions.GetItemByIndex[T](IEnumerable`1 items, Int32 index)
   at AngleSharp.Dom.HtmlCollection`1.get_Item(Int32 index)
   at RssFeeder.Console.TagParsers.TagParserBase.TryAddUlParagraph(StringBuilder description, IElement p) in C:\Projects\RssFeeder\RssFeeder.Console\TagParsers\TagParserBase.cs:line 304
   at RssFeeder.Console.TagParsers.GenericTagParser.BuildArticleText(IHtmlCollection`1 paragraphs) in C:\Projects\RssFeeder\RssFeeder.Console\TagParsers\GenericTagParser.cs:line 63
   at RssFeeder.Console.TagParsers.GenericTagParser.ParseTagsBySelector(ArticleRouteTemplate template) in C:\Projects\RssFeeder\RssFeeder.Console\TagParsers\GenericTagParser.cs:line 36
   at RssFeeder.Console.ArticleParser.Parse(RssFeedItem item) in C:\Projects\RssFeeder\RssFeeder.Console\ArticleParser.cs:line 70
   at RssFeeder.Console.WebCrawler.TryParseAndSave(RssFeed feed, RssFeedItem item) in C:\Projects\RssFeeder\RssFeeder.Console\WebCrawler.cs:line 80
```

**Properties**
```
* Application : "rssfeeder.crawler"
* collectionName : "drudge-report"
* runID : "92f6f6d2-8bb8-4b28-976d-5bf5e911f936"
* url : "https://tulsaworld.com/news/state-and-regional/govt-and-politics/jim-inhofe-looks-back-on-his-career-i-really-wanted-to-make-a-difference-and/article_3e824aaa-9750-11ed-9be6-2fe21d735cfe.html"
* urlHash : "feee7afb66be800f6e6065d53269b5ae"
```

**Comment by mgnoonan** [comment]
Can't reproduce.
